beets:
  image: ghcr.io/linuxserver/beets
  container_name: beets
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
  volumes:
    - </path/to/appdata/config>:/config
    - </path/to/music/library>:/music
    - </path/to/ingest>:/downloads
  ports:
    - 8337:8337
  restart: unless-stopped

bazarr:
  image: ghcr.io/linuxserver/bazarr
  container_name: bazarr
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
  volumes:
    - /path/to/bazarr/config:/config
    - /path/to/movies:/movies #optional
    - /path/to/tv:/tv #optional
  ports:
    - 6767:6767
  restart: unless-stopped

audacity:
  image: ghcr.io/linuxserver/audacity
  container_name: audacity
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
  volumes:
    - /path/to/config:/config
  ports:
    - 3000:3000
  restart: unless-stopped

airsonic:
  image: ghcr.io/linuxserver/airsonic
  container_name: airsonic
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
    - CONTEXT_PATH=<URL_BASE> #optional
    - JAVA_OPTS=<options> #optional
  volumes:
    - </path/to/config>:/config
    - </path/to/music>:/music
    - </path/to/playlists>:/playlists
    - </path/to/podcasts>:/podcasts
    - </path/to/other media>:/media #optional
  ports:
    - 4040:4040
  devices:
    - /dev/snd:/dev/snd #optional
  restart: unless-stopped

wireshark:
  image: ghcr.io/linuxserver/wireshark
  container_name: wireshark
  cap_add:
    - NET_ADMIN
  network_mode: host
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
  volumes:
    - /path/to/config:/config
  ports:
    - 3000:3000 #optional
  restart: unless-stopped

wikijs:
  image: ghcr.io/linuxserver/wikijs
  container_name: wikijs
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
  volumes:
    - <path to config>:/config
    - <path to data>:/data
  ports:
    - 3000:3000
  restart: unless-stopped

webtop:
  image: ghcr.io/linuxserver/webtop
  container_name: webtop
  privileged: true #optional
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
  volumes:
    - /path/to/data:/config
    - /var/run/docker.sock:/var/run/docker.sock #optional
  ports:
    - 3000:3000
  shm_size: "1gb" #optional
  restart: unless-stopped
